### ISSUE TITLE
Guide on error handling

### ISSUE THREAD

**Issue by killercup** [cyclejs/cycle-core#158] opened 2015-07-25 12:58 UTC
First off: Thanks for creating Cycle, @staltz! I really like the way it works (and how it doesn't use neither `class` nor `this`.)

And I'm writing this because I'm not sure what the best way of dealing with errors in a Cycle application is. I couldn't find any documentation on this, so I tried to figure it out myself. The following is basically a Request for Comments. I would love to hear what other Cycle user have to say about this.

I replicated the BMI example from the Cycle docs [here](https://github.com/killercup/cycle-webpack-starter/blob/4a45c8537da92cb1f2c3585dd2626de0b431e15f/app/index.js). Imaging that for some reason the labeled slider could sometimes give you `NaN` and your `calculateBMI` function throws an error when that happens.

_Where and how would you handle the error?_

My first idea was to look for a `mapError` method on the Observable so my view could return different markup when an error happens. My understanding of how Rx treats errors was wrong, though, as errors seem to terminate the stream unless caught. So, I concluded that the error needed to be caught further up the chain, i.e. in `model`, where I could easily add a `.catch` (after `.combineLatest`).

How should the caught error be represented, though? My [first idea](https://github.com/killercup/cycle-webpack-starter/commit/0ba1082d2a4e006b2e4f59dce7208f9a08649425#diff-2018087f584c4398b5c3a23fc0e5f9db) was to use an Object with an `error` key, so I could easily check for it's existence in the view. (Another option would be to send the Error itself, but since I'm not sure it's always `instanceof Error`, it may be hard to check for.)

I'm not really happy with this. It does work, but it's not as elegant as it could be. So, I tried to create some abstractions around that boilerplate code. You can see a working prototype [in this commit](https://github.com/killercup/cycle-webpack-starter/commit/2764aa1beea15112febf6dcc670eb94720769d7a). It basically replaces the one call to `.map(...)` (with an internal error check) with two (`.map(ifOk(...))` and `.map(ifError(...))`).

This is as far as I got. It seems to be extendable enough (`ifInProgress`? Sure!), although it'd be better in the long term to convert the model's stream to contain something like instances of algebraic data types so that I can be confident in identifying errors, data and in-between.

What do you think?

**Comment by staltz** [comment] 2015-07-25 13:05
You're right that error handling was a bit overlooked in the docs and perhaps in the API as well. Some people mentioned "Cycle.js swallows errors", so this is in general a perceived problem. Rx treatment of errors (errors abort/terminate the Observable) is well-known among the Rx community and is one of those gotchas you need to get used to.

I promise to come back to this issue in the near future.

**Comment by maxfrigge** [comment] 2015-11-01 19:38
Greetings from the near future :)

Any progress on this?

**Comment by Frikki** [comment] 2015-11-01 23:38
@maxfrigge There has been other more pressing issues that have been addressed, and so this issue has not yet been progressed.

**Comment by maxfrigge** [comment] 2015-11-02 09:50
Thanks for the heads up.

**Comment by gyzerok** [comment] 2015-12-03 11:56
One more greeting from the near future of near future :D

**Comment by fobos** [comment] 2015-12-04 07:36
Hi folks!

So, this issue is very vital for me and @gyzerok because we are trying to create huge modular application using Cycle.js. 
The main goal for us is to divide the application in separate independent modules/apps with very limited API and number of shared streams by which these apps can interact with each other. I assume that the whole number of such apps will be more than 10...20...more. And we want to divide our development team to separate independent groups that will work with separate number of modules/apps. 

So we want prevent crash of whole app that caused by error in stream of some module. Generally speaking we want decrease mistakes influence of dev groups. More thoughts: the module/app is like a box and all error that happens in that box should not influence on other boxes. We want to create some type of automatic recovery system after errors.

@staltz @Frikki we need your help, guys. Any thoughts, suggestions, ideas are welcome. If you will need some help to work on Cycle core by the issue we will do.

**Comment by staltz** [comment] 2015-12-04 08:31
An update to this issue: when it was created, Cycle core used to swallow error messages. Since then, [this has been fixed](https://github.com/cyclejs/cycle-core/commit/ceb58a5f93e88fdb422b8ef743e484fdfc3c455e). Currently you are able to catch all errors that happen in the app because all the functionality is returned in the sinks object (with Observables for each driver). So in the worst case, you can catch (Rx Operator `.catch()`) all errors at the top-level sink before returning to drivers. You can also put `.catch()` and `.retry()` operators anywhere you wish. The way of handling this is really the Rx way, there isn't much we need to build in Cycle for this.

> So we want prevent crash of whole app that caused by error in stream of some module. Generally speaking we want decrease mistakes influence of dev groups. More thoughts: the module/app is like a box and all error that happens in that box should not influence on other boxes. We want to create some type of automatic recovery system after errors.

You're looking for an architecture that handles errors everywhere, between the boundaries of these subapps. I recommend making that error guarding logic as a function which can be used as an operator, e.g. `safe()` in `var safeVTree$ = safe(vtree$)`. If you need help, ask the Cycle.js community in gitter, ask the RxJS community too (they really know how to use error-handling operators).

Also, I'm closing this issue because I don't know yet (concretely) what could be done for error handling, and this commit https://github.com/cyclejs/cycle-core/commit/ceb58a5f93e88fdb422b8ef743e484fdfc3c455e was made after this promise:

> I promise to come back to this issue in the near future.

I'll try to keep the issues in the repos up-to-date and relevant, but sometimes there are some outdated issues. This was one of them.

**Closed by staltz** 2015-12-04 08:31 UTC
Labels: bug, discussion, feature

**Comment by fobos** [comment] 2015-12-04 08:49
@staltz Thanks for answer. Gonna  see `safe`.
